/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 24 23:30:34 GMT 2018
 */

package org.joda.time;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.joda.time.DateTimeComparator;
import org.joda.time.DateTimeFieldType;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DateTimeComparator_ESTest extends DateTimeComparator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = new DateTimeComparator((DateTimeFieldType) null, (DateTimeFieldType) null);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getDateOnlyInstance();
      // Undeclared exception!
      try { 
        dateTimeComparator0.compare((Object) null, "09A(sC/5");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Invalid format: \"09A(sC/5\" is malformed at \"A(sC/5\"
         //
         verifyException("org.joda.time.format.DateTimeParserBucket", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance();
      DateTimeFieldType dateTimeFieldType0 = dateTimeComparator0.getLowerLimit();
      assertNull(dateTimeFieldType0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getTimeOnlyInstance();
      DateTimeFieldType dateTimeFieldType0 = dateTimeComparator0.getUpperLimit();
      DateTimeComparator dateTimeComparator1 = DateTimeComparator.getInstance(dateTimeFieldType0, (DateTimeFieldType) null);
      assertNotSame(dateTimeComparator0, dateTimeComparator1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getTimeOnlyInstance();
      String string0 = dateTimeComparator0.toString();
      assertEquals("DateTimeComparator[-dayOfYear]", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance();
      String string0 = dateTimeComparator0.toString();
      assertEquals("DateTimeComparator[]", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getDateOnlyInstance();
      String string0 = dateTimeComparator0.toString();
      assertEquals("DateTimeComparator[dayOfYear-]", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getTimeOnlyInstance();
      dateTimeComparator0.hashCode();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance();
      dateTimeComparator0.hashCode();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getDateOnlyInstance();
      dateTimeComparator0.hashCode();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance((DateTimeFieldType) null, (DateTimeFieldType) null);
      DateTimeComparator dateTimeComparator1 = DateTimeComparator.getTimeOnlyInstance();
      boolean boolean0 = dateTimeComparator1.equals(dateTimeComparator0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance((DateTimeFieldType) null, (DateTimeFieldType) null);
      DateTimeComparator dateTimeComparator1 = DateTimeComparator.getTimeOnlyInstance();
      boolean boolean0 = dateTimeComparator0.equals(dateTimeComparator1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance((DateTimeFieldType) null, (DateTimeFieldType) null);
      DateTimeComparator dateTimeComparator1 = DateTimeComparator.getDateOnlyInstance();
      boolean boolean0 = dateTimeComparator1.equals(dateTimeComparator0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance((DateTimeFieldType) null, (DateTimeFieldType) null);
      DateTimeComparator dateTimeComparator1 = DateTimeComparator.getDateOnlyInstance();
      boolean boolean0 = dateTimeComparator0.equals(dateTimeComparator1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance((DateTimeFieldType) null, (DateTimeFieldType) null);
      boolean boolean0 = dateTimeComparator0.equals(dateTimeComparator0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance();
      boolean boolean0 = dateTimeComparator0.equals("09A(sC/5");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance((DateTimeFieldType) null, (DateTimeFieldType) null);
      int int0 = dateTimeComparator0.compare((Object) null, (Object) null);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getDateOnlyInstance();
      DateTimeFieldType dateTimeFieldType0 = dateTimeComparator0.getLowerLimit();
      DateTimeComparator dateTimeComparator1 = DateTimeComparator.getInstance(dateTimeFieldType0);
      assertSame(dateTimeComparator1, dateTimeComparator0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getInstance();
      DateTimeFieldType dateTimeFieldType0 = dateTimeComparator0.getUpperLimit();
      assertNull(dateTimeFieldType0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      DateTimeComparator dateTimeComparator0 = DateTimeComparator.getDateOnlyInstance();
      DateTimeFieldType dateTimeFieldType0 = dateTimeComparator0.getLowerLimit();
      DateTimeComparator dateTimeComparator1 = DateTimeComparator.getInstance(dateTimeFieldType0, dateTimeFieldType0);
      String string0 = dateTimeComparator1.toString();
      assertEquals("DateTimeComparator[dayOfYear]", string0);
  }
}
